version: '3.8'

services:
  myapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      ENV: "dev"
      PORT: "8080"
      POSTGRES_HOST: "db"        
      POSTGRES_PORT: "5432"
      POSTGRES_USER: "recrumsbu"
      POSTGRES_PASSWORD: "recrumsbu"
      POSTGRES_DATABASE: "recrumsbu"
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=recrumsbu
      - POSTGRES_PASSWORD=recrumsbu
      - POSTGRES_DB=recrumsbu
    ports:
      - "5432:5432"