version: '3.8'

services:
  myapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      ENV: "dev"
      PORT: "8080"
      DATABASE_URL: "postgresql://recrumsbu:recrumsbu@db:5432/recrumsbu?schema=public"
      JWT_SECRET: ${JWT_SECRET}
      POSTGRES_HOST: "db"
      POSTGRES_PORT: "5432"
      POSTGRES_USER: "recrumsbu"
      POSTGRES_PASSWORD: "recrumsbu"
      POSTGRES_DATABASE: "recrumsbu"

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=recrumsbu
      - POSTGRES_PASSWORD=recrumsbu
      - POSTGRES_DB=recrumsbu
    ports:
      - "5432:5432"